import { useState, useEffect } from "react";
import {
  MoreHorizontal,
  Square,
  Clock,
  FileText,
  FileCheck,
  Plus,
  X,
  Filter,
  ChevronDown,
  Edit,
  Trash2,
  Search,
} from "lucide-react";
// Sample data structure matching your case class
const initialCases = [
  {
    CaseID: 1,
    Title: "Smith vs. Johnson",
    ClientID: 101,
    status: "Active",
    CreateAt: "2024-01-15",
    UpdateAt: "2024-02-20",
    Documents: ["complaint.pdf", "evidence1.pdf"],
    LeadAttorney: "John Doe",
    PracticeArea: "Family Law",
    Office: "New York",
  },
  {
    CaseID: 2,
    Title: "Doe vs. State",
    ClientID: 102,
    status: "Closed",
    CreateAt: "2024-03-10",
    UpdateAt: "2024-04-12",
    Documents: ["pleading.pdf"],
    LeadAttorney: "Jane Smith",
    PracticeArea: "Criminal Law",
    Office: "Los Angeles",
  },
  {
    CaseID: 3,
    Title: "Williams vs. Davis",
    ClientID: 103,
    status: "Active",
    CreateAt: "2024-02-18",
    UpdateAt: "2024-03-25",
    Documents: ["motion.pdf", "discovery.pdf"],
    LeadAttorney: "Alice Brown",
    PracticeArea: "Corporate Law",
    Office: "Chicago",
  },
  {
    CaseID: 4,
    Title: "Taylor vs. Martinez",
    ClientID: 104,
    status: "Pending",
    CreateAt: "2024-05-10",
    UpdateAt: "2024-06-15",
    Documents: ["contract.pdf"],
    LeadAttorney: "Michael Green",
    PracticeArea: "Contract Law",
    Office: "Miami",
  },
  {
    CaseID: 5,
    Title: "Garcia vs. Evans",
    ClientID: 105,
    status: "Closed",
    CreateAt: "2023-11-01",
    UpdateAt: "2023-12-20",
    Documents: ["settlement.pdf"],
    LeadAttorney: "Laura Johnson",
    PracticeArea: "Real Estate Law",
    Office: "Houston",
  },
  {
    CaseID: 6,
    Title: "Brown vs. Robinson",
    ClientID: 106,
    status: "Active",
    CreateAt: "2024-02-05",
    UpdateAt: "2024-03-12",
    Documents: ["evidence2.pdf", "summary.pdf"],
    LeadAttorney: "David Miller",
    PracticeArea: "Personal Injury",
    Office: "San Francisco",
  },
  {
    CaseID: 7,
    Title: "Anderson vs. Clark",
    ClientID: 107,
    status: "Active",
    CreateAt: "2024-04-08",
    UpdateAt: "2024-05-10",
    Documents: ["affidavit.pdf", "testimony.pdf"],
    LeadAttorney: "Emma Lee",
    PracticeArea: "Employment Law",
    Office: "Seattle",
  },
  {
    CaseID: 8,
    Title: "Harris vs. Lewis",
    ClientID: 108,
    status: "Pending",
    CreateAt: "2024-03-15",
    UpdateAt: "2024-04-18",
    Documents: ["agreement.pdf"],
    LeadAttorney: "Robert Wilson",
    PracticeArea: "Bankruptcy Law",
    Office: "Denver",
  },
  {
    CaseID: 9,
    Title: "Martinez vs. White",
    ClientID: 109,
    status: "Active",
    CreateAt: "2024-05-22",
    UpdateAt: "2024-06-29",
    Documents: ["complaint.pdf", "motion2.pdf"],
    LeadAttorney: "Sophia Hernandez",
    PracticeArea: "Intellectual Property",
    Office: "Austin",
  },
  {
    CaseID: 10,
    Title: "Moore vs. Gonzalez",
    ClientID: 110,
    status: "Closed",
    CreateAt: "2023-10-15",
    UpdateAt: "2023-12-01",
    Documents: ["contract_dispute.pdf"],
    LeadAttorney: "William Martinez",
    PracticeArea: "Business Law",
    Office: "Boston",
  },
  {
    CaseID: 11,
    Title: "King vs. Wright",
    ClientID: 111,
    status: "Pending",
    CreateAt: "2024-01-20",
    UpdateAt: "2024-03-05",
    Documents: ["subpoena.pdf", "exhibit1.pdf"],
    LeadAttorney: "Olivia Taylor",
    PracticeArea: "Civil Rights Law",
    Office: "Washington, D.C.",
  },
  {
    CaseID: 12,
    Title: "Hill vs. Scott",
    ClientID: 112,
    status: "Active",
    CreateAt: "2024-06-12",
    UpdateAt: "2024-07-01",
    Documents: ["witness_statement.pdf"],
    LeadAttorney: "James Harris",
    PracticeArea: "Immigration Law",
    Office: "Phoenix",
  },
  {
    CaseID: 13,
    Title: "Young vs. Adams",
    ClientID: 113,
    status: "Closed",
    CreateAt: "2023-09-30",
    UpdateAt: "2023-11-10",
    Documents: ["settlement_agreement.pdf"],
    LeadAttorney: "Charlotte King",
    PracticeArea: "Family Law",
    Office: "Philadelphia",
  },
  {
    CaseID: 14,
    Title: "Walker vs. Nelson",
    ClientID: 114,
    status: "Active",
    CreateAt: "2024-07-05",
    UpdateAt: "2024-08-10",
    Documents: ["petition.pdf", "deposition.pdf"],
    LeadAttorney: "Ethan Parker",
    PracticeArea: "Tax Law",
    Office: "San Diego",
  },
];

const filterOptions = {
  LeadAttorney: ["John Doe", "Jane Smith", "Bob Wilson"],
  PracticeArea: ["Family Law", "Criminal Law", "Corporate Law", "Real Estate"],
  Office: ["New York", "Los Angeles", "Chicago", "Houston"],
  status: ["Active", "Pending", "Closed"],
};
